# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/bionic64"

	config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end

	config.vm.network "private_network", type: "dhcp"
	# MySQL
	config.vm.network "forwarded_port", guest: 3306, host: 33306
	# PG
	config.vm.network "forwarded_port", guest: 5432, host: 35432
	# CouchDB UI
	config.vm.network "forwarded_port", guest: 5984, host: 35984


	config.vm.provision "shell", path: "provision.sh"
  # config.vm.network "public_network"
end
